FROM golang:alpine as build

WORKDIR /app

COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o server -ldflags="-w -s" cmd/rpc/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/server .

EXPOSE 50051

CMD ["./server"]
